server:
  applicationConnectors:
    - type: http
      port: 3000
  adminConnectors:
    - type: http
      port: 3001

logging:
  level: INFO
  loggers:
    com.aakn.workstore: DEBUG
  appenders:
    - type: console

clientConfiguration:
  minThreads: 1
  maxThreads: 8