server:
  applicationConnectors:
    - type: http
      port: 3000
  adminConnectors:
    - type: http
      port: 3001

logging:
  level: INFO
  loggers:
    com.aakn.workstore: DEBUG
  appenders:
    - type: console

clientConfiguration:
  minThreads: 1
  maxThreads: 8
  timeout: 2s
  connectionTimeout: 2s

databaseConfiguration:
  driverClass: org.h2.Driver
  user: sa
  password:
  url: jdbc:h2:./db/work-store-memory-db.h2;DB_CLOSE_ON_EXIT=FALSE
  properties:
    charSet: UTF-8
    hibernate.hbm2ddl.auto: update
  maxWaitForConnection: 1s
  validationQuery: "/* MyService Health Check */ SELECT 1"
  minSize: 1
  maxSize: 20
  validationInterval: 10s
  minIdleTime: 1 minute

viewConfiguration:
  .ftl:
    strict_syntax: yes
    cache: false
